<?php

namespace Database\Seeders;

use App\Enums\FacilityType;
use App\Models\Facility;
use App\Models\Major;
use Illuminate\Database\Seeder;

/**
 * Data awal fasilitas, dipindahkan dari data statis halaman fasilitas
 * (14 titik denah, daftar TEFA, grid fasilitas unggulan & modal).
 * Foto memakai versi .webp. Jalankan setelah MajorSeeder.
 */
class FacilitySeeder extends Seeder
{
    public function run(): void
    {
        $majorIds = Major::pluck('id', 'slug');

        $facilities = [
            [
                'slug' => 'tefa-dkv',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Tefa SMEMSA Printing (DKV)',
                'short_name' => 'Tefa SMEMSA Printing',
                'mark' => 'DKV',
                'tag' => 'Teaching Factory · DKV',
                'location_label' => 'Sekolah Utara — Tenggara',
                'description' => 'Unit produksi percetakan dan merchandise komersial yang mengerjakan pesanan nyata dari sekolah, instansi, dan masyarakat umum.',
                'features' => ['Digital Press A3+', 'Mesin Cetak Offset', 'Cutting & Laminasi', 'Sablon DTF & Merchandise'],
                'highlight' => 'Siswa terlibat langsung dari penawaran harga, pra-cetak, finishing, hingga penyerahan produk ke pelanggan.',
                'short_description' => null,
                'icon' => 'printer',
                'major' => 'dkv',
                'map_x' => 849,
                'map_y' => 485,
                'show_in_tefa_list' => true,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 10,
                'photo' => 'assets/view/view-1.webp',
            ],
            [
                'slug' => 'tefa-surya',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Surya Mart (Bisnis Digital)',
                'short_name' => 'Surya Mart',
                'mark' => 'SM',
                'tag' => 'Teaching Factory · Bisnis Digital',
                'location_label' => 'Sekolah Utara — Tenggara',
                'description' => 'Minimarket ritel sekolah yang dikelola langsung oleh siswa Bisnis Digital, melayani kebutuhan harian seluruh warga sekolah.',
                'features' => ['Sistem Kasir POS', 'Manajemen Stok & FIFO', 'Display Produk Ritel', 'Laporan Penjualan Harian'],
                'highlight' => 'Siswa mempraktikkan inventory control, kasir barcode, dan customer handling secara langsung.',
                'short_description' => null,
                'icon' => 'building',
                'major' => 'bd',
                'map_x' => 783,
                'map_y' => 485,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 20,
                'photo' => 'assets/view/view-3.webp',
            ],
            [
                'slug' => 'tefa-pegadaian',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Agen Pegadaian Mentari SMEMSA',
                'short_name' => 'Agen Pegadaian Mentari',
                'mark' => 'PGD',
                'tag' => 'Teaching Factory · Manajemen Perkantoran',
                'location_label' => 'Sekolah Utara — Tenggara',
                'description' => 'Kemitraan resmi dengan PT Pegadaian untuk layanan tabungan emas, multi-payment, dan transaksi mikro bagi masyarakat.',
                'features' => ['Loket Transaksi Resmi', 'Sistem Online Pegadaian', 'Administrasi Dokumen', 'Pelayanan Nasabah'],
                'highlight' => 'Siswa MPLB mempraktikkan etika front-office dan transaksi keuangan legal berstandar BUMN.',
                'short_description' => null,
                'icon' => 'card',
                'major' => 'mplb',
                'map_x' => 718,
                'map_y' => 485,
                'show_in_tefa_list' => true,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 30,
                'photo' => 'assets/view/view-2.webp',
            ],
            [
                'slug' => 'tefa-bms',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Bank Mini Sekolah (BMS) BTM',
                'short_name' => 'Bank Mini Sekolah',
                'mark' => 'BMS',
                'tag' => 'Teaching Factory · Akuntansi',
                'location_label' => 'Sekolah Utara — Tenggara',
                'description' => 'Lembaga keuangan mikro sekolah untuk tabungan harian siswa, kas ekstrakurikuler, dan simulasi perbankan syariah.',
                'features' => ['Aplikasi Core Banking', 'Mesin Hitung Uang', 'Buku Tabungan Barcode', 'Simulasi Teller & CS'],
                'highlight' => 'Siswa AKL membukukan ribuan transaksi riil setiap semester dengan pembukuan ganda.',
                'short_description' => null,
                'icon' => 'bank',
                'major' => 'akl',
                'map_x' => 656,
                'map_y' => 485,
                'show_in_tefa_list' => true,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 40,
                'photo' => 'assets/view/view-4.webp',
            ],
            [
                'slug' => 'tefa-edotel',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Edotel SMEMSA (Guest House)',
                'short_name' => 'Edotel SMEMSA',
                'mark' => 'EDO',
                'tag' => 'Teaching Factory · Perhotelan',
                'location_label' => 'Sekolah Selatan',
                'description' => 'Fasilitas penginapan edukatif dengan 3 unit kamar berstandar hotel, lobby, dan ruang pertemuan untuk tamu sekolah maupun umum.',
                'features' => ['Front Office', 'Home Stay 1–3', 'Sistem Reservasi', 'Housekeeping'],
                'highlight' => 'Siswa Perhotelan mempraktikkan resepsionis dan housekeeping pada tamu sungguhan.',
                'short_description' => null,
                'icon' => 'hotel',
                'major' => 'ph',
                'map_x' => 260,
                'map_y' => 697,
                'show_in_tefa_list' => true,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 50,
                'photo' => 'assets/view/view-1.webp',
            ],
            [
                'slug' => 'tefa-laundry',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Lab. Laundry (Sun Wash)',
                'short_name' => 'Lab. Laundry',
                'mark' => 'LDR',
                'tag' => 'Teaching Factory · Perhotelan',
                'location_label' => 'Sekolah Selatan',
                'description' => 'Unit binatu profesional yang melayani linen hotel maupun pakaian warga sekitar, sekaligus menjadi ruang praktik pengelolaan tekstil.',
                'features' => ['Mesin Cuci Industri', 'Pengering & Setrika Uap', 'Sortir Linen', 'Layanan Pelanggan'],
                'highlight' => 'Melengkapi rantai layanan eDotel — siswa belajar operasional binatu komersial.',
                'short_description' => null,
                'icon' => 'hotel',
                'major' => 'ph',
                'map_x' => 312,
                'map_y' => 697,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 60,
                'photo' => 'assets/view/view-5.webp',
            ],
            [
                'slug' => 'fac-masjid',
                'type' => FacilityType::Supporting,
                'name' => 'Masjid Namiroh',
                'short_name' => 'Masjid Namiroh',
                'mark' => 'MSJ',
                'tag' => 'Fasilitas · Ibadah',
                'location_label' => 'Sekolah Utara — Tengah',
                'description' => 'Pusat kegiatan ibadah dan pembinaan keislaman warga sekolah, meliputi salat berjamaah, kajian rutin, dan kegiatan keagamaan.',
                'features' => ['Ruang Salat Utama', 'Tempat Wudu', 'Area Kajian', 'Koleksi Islami'],
                'highlight' => 'Pusat pembinaan akhlak Islami berkemajuan di lingkungan sekolah.',
                'short_description' => null,
                'icon' => 'building',
                'major' => null,
                'map_x' => 366,
                'map_y' => 108,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 70,
                'photo' => 'assets/view/view-5.webp',
            ],
            [
                'slug' => 'fac-lapangan',
                'type' => FacilityType::Supporting,
                'name' => 'Lapangan Utama Multi-Fungsi',
                'short_name' => 'Sarana Olahraga Terpadu',
                'mark' => 'LAP',
                'tag' => 'Fasilitas · Olahraga',
                'location_label' => 'Sekolah Utara — Tengah',
                'description' => 'Lapangan serbaguna untuk basket, futsal, dan voli yang juga digunakan sebagai tempat upacara serta latihan Hizbul Wathan dan Tapak Suci.',
                'features' => ['Lapangan Multi-Fungsi', 'Ring Basket', 'Area Upacara', 'Latihan Kepanduan'],
                'highlight' => 'Pusat kegiatan ekstrakurikuler fisik dan pembinaan kedisiplinan.',
                'short_description' => 'Wadah pengembangan minat dan bakat fisik siswa. Kami menyediakan infrastruktur lengkap meliputi Lapangan Basket, Futsal, Bola Voli, Badminton, hingga fasilitas Tenis Meja.',
                'icon' => 'sport',
                'major' => null,
                'map_x' => 322,
                'map_y' => 320,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => false,
                'sort_order' => 80,
                'photo' => 'assets/view/view-2.webp',
            ],
            [
                'slug' => 'fac-perpus',
                'type' => FacilityType::Supporting,
                'name' => 'Ruang Perpustakaan',
                'short_name' => 'Perpustakaan Digital',
                'mark' => 'PRP',
                'tag' => 'Fasilitas · Literasi',
                'location_label' => 'Sekolah Utara — Barat Daya',
                'description' => 'Koleksi cetak dan digital dengan ruang baca serta area diskusi kelompok untuk mendukung proyek kejuruan siswa.',
                'features' => ['Katalog Koleksi', 'Ruang Baca', 'Area Diskusi', 'Referensi Kejuruan'],
                'highlight' => 'Ruang kerja favorit siswa saat menggarap proyek akhir kejuruan.',
                'short_description' => 'Pusat sumber belajar dengan koleksi buku dan jurnal yang komprehensif. Selain literatur cetak, perpustakaan ini juga menyediakan akses penuh ke sumber daya digital dan internet untuk riset mendalam.',
                'icon' => 'book',
                'major' => null,
                'map_x' => 300,
                'map_y' => 465,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => false,
                'sort_order' => 90,
                'photo' => 'assets/view/view-4.webp',
            ],
            [
                'slug' => 'fac-lab',
                'type' => FacilityType::Supporting,
                'name' => 'Deret Ruang Laboratorium',
                'short_name' => 'Laboratorium Komputer',
                'mark' => 'LAB',
                'tag' => 'Fasilitas · Teknologi',
                'location_label' => 'Sekolah Utara — Sisi Barat',
                'description' => 'Rangkaian ruang praktik untuk pemrograman, desain grafis, konfigurasi jaringan, dan penguasaan aplikasi perangkat lunak.',
                'features' => ['PC Spesifikasi Praktik', 'Software Berlisensi', 'Jaringan Lab', 'Proyektor'],
                'highlight' => 'Digunakan bergantian oleh siswa PPLG, TJKT, dan Bisnis Digital sepanjang hari.',
                'short_description' => 'Dilengkapi dengan perangkat komputer terkini yang mendukung proses pembelajaran IT. Tempat ideal bagi siswa untuk praktik pemrograman, desain grafis, jaringan, dan penguasaan aplikasi perangkat lunak.',
                'icon' => 'computer',
                'major' => null,
                'map_x' => 146,
                'map_y' => 321,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => false,
                'sort_order' => 100,
                'photo' => 'assets/view/view-3.webp',
            ],
            [
                'slug' => 'fac-rps',
                'type' => FacilityType::Supporting,
                'name' => 'Ruang Praktik Siswa (RPS 1–3)',
                'short_name' => 'Ruang Praktik Siswa (RPS)',
                'mark' => 'RPS',
                'tag' => 'Fasilitas · Praktik',
                'location_label' => 'Sekolah Utara — Timur Laut',
                'description' => 'Tiga ruang praktik kejuruan berukuran besar untuk kegiatan produktif yang membutuhkan peralatan dan area kerja luas.',
                'features' => ['Area Kerja Luas', 'Peralatan Kejuruan', 'Meja Praktik', 'Penyimpanan Alat'],
                'highlight' => 'Ruang praktik utama untuk kegiatan produktif berskala besar.',
                'short_description' => null,
                'icon' => 'building',
                'major' => null,
                'map_x' => 915,
                'map_y' => 152,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 110,
                'photo' => 'assets/view/view-1.webp',
            ],
            [
                'slug' => 'fac-ballroom',
                'type' => FacilityType::Supporting,
                'name' => 'SMEMSA Ballroom',
                'short_name' => 'SMEMSA Ball Room & Convention',
                'mark' => 'BLR',
                'tag' => 'Fasilitas · Acara',
                'location_label' => 'Sekolah Selatan',
                'description' => 'Aula berkapasitas besar untuk wisuda, seminar, dan pelatihan industri — juga disewakan untuk acara masyarakat sekitar.',
                'features' => ['Tata Suara', 'Panggung', 'Area Resepsi', 'Ruang Persiapan'],
                'highlight' => 'Menjadi ruang praktik langsung siswa Perhotelan dalam manajemen event.',
                'short_description' => 'Ruang serbaguna representatif yang terintegrasi di kompleks perhotelan sekolah. Ideal dan sering digunakan untuk pelaksanaan meeting, seminar, rapat, maupun kegiatan seremonial formal lainnya.',
                'icon' => 'building',
                'major' => null,
                'map_x' => 312,
                'map_y' => 740,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => false,
                'sort_order' => 120,
                'photo' => 'assets/view/view-4.webp',
            ],
            [
                'slug' => 'fac-uks',
                'type' => FacilityType::Supporting,
                'name' => 'Ruang UKS',
                'short_name' => 'Ruang UKS',
                'mark' => 'UKS',
                'tag' => 'Fasilitas · Kesehatan',
                'location_label' => 'Sekolah Utara — Tengah',
                'description' => 'Unit Kesehatan Sekolah untuk penanganan pertama, pemeriksaan berkala, dan basis kegiatan PMR.',
                'features' => ['Ruang Periksa', 'Perlengkapan P3K', 'Tempat Istirahat', 'Basis PMR'],
                'highlight' => 'Bekerja sama dengan BK dalam program layanan kesehatan siswa.',
                'short_description' => null,
                'icon' => 'building',
                'major' => null,
                'map_x' => 236,
                'map_y' => 228,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 130,
                'photo' => 'assets/view/view-2.webp',
            ],
            [
                'slug' => 'fac-admin',
                'type' => FacilityType::Supporting,
                'name' => 'R. Kepala Sekolah & Tata Usaha',
                'short_name' => 'Kepala Sekolah & Tata Usaha',
                'mark' => 'ADM',
                'tag' => 'Fasilitas · Administrasi',
                'location_label' => 'Sekolah Utara — Tengah',
                'description' => 'Pusat administrasi dan pimpinan sekolah, meliputi layanan surat-menyurat, data siswa, serta penerimaan tamu.',
                'features' => ['Ruang Pimpinan', 'Layanan Administrasi', 'Ruang Tamu', 'Arsip Sekolah'],
                'highlight' => 'Titik pertama bagi tamu dan orang tua yang berkunjung ke sekolah.',
                'short_description' => null,
                'icon' => 'building',
                'major' => null,
                'map_x' => 539,
                'map_y' => 132,
                'show_in_tefa_list' => false,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 140,
                'photo' => 'assets/view/view-1.webp',
            ],
            [
                'slug' => 'tekaje',
                'type' => FacilityType::TeachingFactory,
                'name' => 'Tefa Tekaje Solution & ISP Support',
                'short_name' => 'Tefa Tekaje Solution',
                'mark' => 'TKJ',
                'tag' => 'Teaching Factory · TJKT',
                'location_label' => null,
                'description' => 'Unit layanan jasa instalasi jaringan fiber optik, perakitan PC server, konfigurasi perangkat jaringan MikroTik/Cisco, dan maintenance perangkat IT untuk instansi sekolah maupun mitra.',
                'features' => ['Splicer Fiber Optik & OTDR Tester', 'Server Rack & Enterprise Switch', 'Toolkit Maintenance Komputer Lengkap', 'Jasa Perbaikan Hardware & Software', 'Monitoring Bandwidth Management'],
                'highlight' => 'Mengasah kesiapan mental teknisi jaringan siswa untuk menangani troubleshooting jaringan riil dan sertifikasi kompetensi industri internasional.',
                'short_description' => null,
                'icon' => 'network',
                'major' => 'tkj',
                'map_x' => null,
                'map_y' => null,
                'show_in_tefa_list' => true,
                'is_featured' => false,
                'is_wide' => false,
                'sort_order' => 145,
                'photo' => null,
            ],
            [
                'slug' => 'fac-studio',
                'type' => FacilityType::Supporting,
                'name' => 'Studio Desain Komunikasi Visual & Podcast',
                'short_name' => 'Studio Desain & Multimedia',
                'mark' => 'STD',
                'tag' => 'Fasilitas · Kreatif',
                'location_label' => null,
                'description' => 'Fasilitas produksi konten kreatif dengan ruang kedap suara, pencahayaan studio sinematik (Godox/Aputure), kamera 4K, backdrop green screen, dan set rekaman podcast profesional.',
                'features' => ['Set Pencahayaan Studio Multi-Point', 'Kamera Cinema 4K & Audio Wireless Mic', 'Soundproofing Acoustic Wall', 'Workstation Video Editing RTX Series', 'Green Screen Cyclorama'],
                'highlight' => 'Menyediakan ruang eksplorasi total bagi talenta muda perfilman, videografi, animasi, dan siaran podcast digital.',
                'short_description' => 'Ruang kreatif yang dirancang khusus dengan peralatan multimedia terkini. Lingkungan yang kondusif bagi siswa DKV untuk bereksplorasi dalam ilustrasi, animasi, dan produksi media visual profesional.',
                'icon' => 'design',
                'major' => 'dkv',
                'map_x' => null,
                'map_y' => null,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => false,
                'sort_order' => 106,
                'photo' => null,
            ],
            [
                'slug' => 'fac-wifi',
                'type' => FacilityType::Supporting,
                'name' => 'Infrastruktur Wi-Fi Fiber Optik 1 Gbps',
                'short_name' => 'Konektivitas Wi-Fi Berkecepatan Tinggi',
                'mark' => 'WIFI',
                'tag' => 'Fasilitas · Infrastruktur Digital',
                'location_label' => null,
                'description' => 'Jaringan backbone fiber optik terintegrasi dengan puluhan access point enterprise di setiap ruang kelas, bengkel TEFA, dan area publik sekolah dengan alokasi bandwidth merata dan aman.',
                'features' => ['Backbone Fiber Optik 1 Gbps', 'Access Point Wi-Fi 6 Enterprise', 'Firewall & Content Filtering Aman', 'Bandwidth Management QoS', 'Coverage 100% Area Sekolah'],
                'highlight' => 'Memfasilitasi blended learning, akses sumber belajar digital internasional, dan riset teknologi terkini secara instan.',
                'short_description' => 'Mendukung proses pembelajaran digital (e-learning) tanpa batas. Jaringan Wi-Fi berkecepatan tinggi tersedia di seluruh area kelas maupun lingkungan sekolah, dapat diakses penuh oleh siswa dan staf agar senantiasa terhubung dengan teknologi dan sumber literasi global terkini.',
                'icon' => 'wifi',
                'major' => null,
                'map_x' => null,
                'map_y' => null,
                'show_in_tefa_list' => false,
                'is_featured' => true,
                'is_wide' => true,
                'sort_order' => 105,
                'photo' => null,
            ],
        ];

        foreach ($facilities as $data) {
            $photo = $data['photo'];
            $majorSlug = $data['major'];
            unset($data['photo'], $data['major']);

            $facility = Facility::updateOrCreate(
                ['slug' => $data['slug']],
                $data + ['major_id' => $majorSlug ? ($majorIds[$majorSlug] ?? null) : null],
            );

            // Foto denah lama adalah foto contoh, keterangannya ikut ditampilkan.
            if ($photo) {
                $facility->images()->updateOrCreate(
                    ['path' => $photo],
                    ['caption' => 'Foto contoh', 'sort_order' => 1],
                );
            }
        }
    }
}
